# Generated by Django 6.1.1 on 2026-09-17 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Generic Bank Name', max_length=32)),
                ('address', models.CharField(default='Generic Bank Address', max_length=64)),
                ('status', models.BooleanField(default=True)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('update', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Generic Account Name', max_length=32)),
                ('currency', models.CharField(choices=[('MXN', 'Peso Mexicano'), ('USD', 'Dolar americano'), ('EUR', 'Euro')], max_length=16)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('update', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bank')),
            ],
        ),
    ]
